### ISSUE TITLE
I tried eBay Sample OAuth2 failed 

### ISSUE THREAD

**Issue by anhtathai** [googleworkspace/apps-script-oauth2#247]
Here is a  result! 
![temp-1](https://user-images.githubusercontent.com/64001976/96847357-48378e00-147d-11eb-95b8-8709fafde329.png)

I
![temp-1](https://user-images.githubusercontent.com/64001976/96847498-74eba580-147d-11eb-9961-109a25914ad0.png)

I got wrong but don't know why?

Please help!

**Comment by erickoledadevrel** [comment]
The sample included in this repo doesn't include "Response Result:" so it looks like you are doing something custom. What happens when you run the sample as-is? Do you get a token?

**Comment by erickoledadevrel** [comment]
Closing due to lack of response.
