### ISSUE TITLE
Handle multiple services

### ISSUE THREAD

**Issue by etatus** [googleworkspace/apps-script-oauth2#256]
I can't find a way to connect to more than one service.  When you connect a new service, It seems stored data are replaced, so  you cannot handle more than one service (access token) at the same time. Is there any way to solve this?

**Comment by contributorpw** [comment]
Do you use services naming?

`OAuth2.createService('drive')`
`OAuth2.createService('vk')`
etc.

**Comment by etatus** [comment]
Ok, then OAuth2.createService('name_of_service') not only creates the service but also returns the corresponding token if the service is already created. Is this right?

**Comment by erickoledadevrel** [comment]
Yes, that's correct. The name of the service is part of the key used to store and retrieve tokens.

**Comment by etatus** [comment]
Ok, thank you. I guess the library doesn't provide the list of created services, so a possible way to do that would be:

```
var keys = userProperties.getKeys();
var services_names = Array();
for (var i = 0; i < keys.length; i++) {
        if ( keys[i].indexOf('oauth2.') === 0 ) services_names.push( keys[i].split('oauth2.')[1] );
}
```

Is there a more "ellegant" way to do this? Maybe could be an interesting feature to add to the library.

**Comment by erickoledadevrel** [comment]
Ya, that could be something we add to the library. How would you use that function though? In my experience most often the services are more fixed and known to the script.

**Comment by etatus** [comment]
In my case, I need to show all the connected services to the user and give him/her the option of adding more or disconnecting them (individually). For instance, Stripe handles different accounts with a single user that would correspond to different services.

In general, I guess this make sense when you have to keep several services connected (Stripe accounts in my case) because the user is going to use them frequently.

**Comment by etatus** [comment]
BTW, a very simple way to facilitate the manage of multiples services is that the library store them under the same property, as a list of service objects. In this way, you only need to read one property (let's say oauth2):

```
var services =  userProperties.getProperty( 'oauth2' );

// Result: { 'service_name1':serviceObject1, 'service_name2':serviceObject2 }
```

**Comment by erickoledadevrel** [comment]
I've added `OAuth2.getServiceNames(propertyStore)` for this purpose. Since service can be saved to different types of properties you need to pass in the store. I've not used a single property to track them, as that could run into concurrency issues, but filtering the properties is simple and performant enough.

**Comment by etatus** [comment]
Thank you! This function helps a lot in handling multiple services. 

Just one important question: the more recent service is the first one (index 0) or the last one in the service names array returned by the function?

**Comment by erickoledadevrel** [comment]
The function doesn't make any guarantee about the order of the returned services. However you could encode the creation date in the service name (for example `stipe_20201215T123000`) or setting it as a custom property in the service's storage:

```
function authCallback(request) {
  var service = getService();
  var authorized = service.handleCallback(request);
  if (authorized) {
    service.getStorage().setValue('creation_date', (new Date()).toISOString());
    return HtmlService.createHtmlOutput('Success!');
  } else {
    return HtmlService.createHtmlOutput('Denied.');
  }
}
```

**Comment by etatus** [comment]
Hmmm that's not good news. I'd expect the library (and the function) could guarantee the correct order of the services.

I have 2 ideas I  hope you can consider that could solve the problem:

1. To manage the storage of services as an array in an unique property so the library just push() new services and splice() the deleted ones. Thus, OAuth2.getServiceNames() will always return a sorted array of service names.

2. To include a timestamp internally as part of the property of each service in a way OAuth2.getServiceNames() and return the correct order and optionally the timestamps (this would be awesome!).

```
var timestamp = new Date().getTime();
var service_property = 'oauth2.'+timestamp+'.'+service_name;

var timestamp = service_property.split('.')[1];
```

**Comment by erickoledadevrel** [comment]
I don't think it makes sense to implement ordering in the library, given the methods I outlined for implementing it yourself and that this is a fairly niche feature.

**Comment by etatus** [comment]
Sorry, I guess I disagree. It's quite strange for me that the items of an array returned by a function could be in different positions everytime you call it without any criteria (this is computer science!). I'm not telling that the order has to be necessarily the creation timestamp, but at least the criteria should be known in order to get more deterministic results.

Thank you anyway for your amazing library!
