### ISSUE TITLE
Service account’s ID token can’t get refreshed

### ISSUE THREAD

**Issue by ygriku** [googleworkspace/apps-script-oauth2#257]
I am using the sample code (samples/CloudIdentityAwareProxy.gs) in my apps script to call APIs of an IAP-secured GAE with a service account. It works fine at first, but it fails one hour after the acquisition of the ID token. The log says:
“OpenID Connect token expired: JWT has expired”

This is apparently because the function isExpired_() in Service.js is not aware of the exp (expiration time) claim in the JWT. 

```
Service_.prototype.isExpired_ = function(token) {
  var expiresIn = token.expires_in_sec || token.expires_in || token.expires;
  if (!expiresIn) {
    return false;
  } else {
    var expiresTime = token.granted_time + Number(expiresIn);
    var now = getTimeInSeconds_(new Date());
    return expiresTime - now < Service_.EXPIRATION_BUFFER_SECONDS_;
  }
};
```

I suppose that the code can be like this:
```
Service_.prototype.isExpired_ = function(token) {
  var expiresIn = token.expires_in_sec || token.expires_in || token.expires;
  var now = getTimeInSeconds_(new Date());

  if (!expiresIn) {
    // Look for the expiration time claim in JWT's payload
    var token_fields = token.id_token.split('.')
    var payload_b = Utilities.base64DecodeWebSafe(token_fields[1])
    var payload = JSON.parse(Utilities.newBlob(payload_b).getDataAsString())
    var expires_at = payload.exp
    if (!expires_at){
      return false;
    }
    return expires_at - now < Service_.EXPIRATION_BUFFER_SECONDS_;
  } else {
    var expiresTime = token.granted_time + Number(expiresIn);
    return expiresTime - now < Service_.EXPIRATION_BUFFER_SECONDS_;
  }
};
```

The modified code works well at my site to refresh the credentials. 

While I guess this post might help someone who stumbled on this matter, I am not confident whether this modification does not cause any untoward effect. I appreciate your comments.

**Comment by erickoledadevrel** [comment]
Thanks for the detailed issue report and sample solution. I modified it a bit to handle the case where there is both an authorization token and ID token.
