### ISSUE TITLE
Unable to get id token from google

### ISSUE THREAD

**Issue by baymac** [googleworkspace/apps-script-oauth2#265]
Is there a way to get id token using google as oauth provider? TIA.

**Comment by baymac** [comment]
Got it, using `getToken()`

**Comment by erickoledadevrel** [comment]
There is also a [`Service.getIdToken()`](http://googleworkspace.github.io/apps-script-oauth2/Service_.html#getIdToken) method that you can use for that purpose.

**Comment by baymac** [comment]
@erickoledadevrel Thanks. On another note, the id token issued by this library compared to gapi (google apis js client) are different. On the server side when I am verifying the ID token using Google's Java client as :

```java
GoogleIdTokenVerifier.Builder(httpTransport, jsonFactory)
                .setAudience(listOf("<client_id>"))
                .setIssuer("accounts.google.com")
                .build().verify("<id_token>")
``` 

The above code returns false for the id token issued by `apps-script-oauth2` while it returns true for id token issued by gapi. The difference between both tokens are:

1. `apps-script-oauth2`'s token has `iss` as `https://accounts.google.com` while `gapi`'s token has `iss` as `accounts.google.com`
2.  `apps-script-oauth2`'s token doesn't have a field as `jti` while `gapi`'s token has `jti`

Do you have any idea on this?

**Comment by erickoledadevrel** [comment]
It looks like you are explicitly setting an issuer of "accounts.google.com" in your Java code, which as you said doesn't match what the value is set to in the token you obtained from this library. It looks like the library by default [allows both issuers](https://github.com/googleapis/google-api-java-client/blob/c310c1c61fba47dcb396a0e4ced2874f11c5a8af/google-api-client/src/main/java/com/google/api/client/googleapis/auth/oauth2/GoogleIdTokenVerifier.java#L233), so I think if you remove the `.setIssuer()` call from your Java code it should work.
