### ISSUE TITLE
All methods fail with server error with Chrome V8 runtime

### ISSUE THREAD

**Issue by SeanYang66** [googleworkspace/apps-script-oauth2#267]
Hi I'm trying to use this library and have met a few issues. One of them is that all my methods fail with an error "We're sorry, a server error occurred while reading from storage. Error code NOT_FOUND." when I'm using Chrome V8 runtime. They do execute (although I'm still battling other issues) when I turn V8 off.

I've tried sign off multiple accounts other than the one owning the sheet, as well as using incognito, but still got the same error.

**Comment by erickoledadevrel** [comment]
There are some reports of people having trouble using this library with V8, but not with that error message. Can you determine if the library is loaded at all? What version are you using?

**Comment by SeanYang66** [comment]
Okay I think I installed an old version. I've now copied the source code to my project and it works in V8 as well. Thanks for pointing that out.
