### ISSUE TITLE
Failure retrieving token from TD Ameritrade callback

### ISSUE THREAD

**Issue by SeanYang66** [googleworkspace/apps-script-oauth2#268]
Hi, I'm trying to connect to TD Ameritrade API with this library, and I'm getting 
```
Error: Error retrieving token: 401: {"\n {\n \"error\":\"The API key in request is either null or blank or invalid.\"\n \t\t}\n ":"undefined","granted_time":1613351996} (line 541, file "Service", project "OAuth2")
```
from the callback.
Below is the callback request format from TD (I'm using WebApp url because I am facing the same issue in #137 )
```
https://script.google.com/macros/s/<web app id>/exec?code=<URL encoded authorization code>
```

I am setting `.setTokenFormat(OAuth2.TOKEN_FORMAT.FORM_URL_ENCODED)` in `OAuth2.createService()`. What did I miss?

**Comment by SeanYang66** [comment]
I was able to figure the correct request to send to TD, but I had to modify the library to do that.

Specifically the library always set header
```
{Accept=application/x-www-form-urlencoded}
```
But TD requires 
```
{Content-Type=application/x-www-form-urlencoded}
```
And there's only API to extend the header but not replacing the default `Accept` one. Not sure if it should be added?

**Comment by erickoledadevrel** [comment]
The `Content-Type` header should default to that value, as per the Apps Script documentation on `UrlFetchApp`:

https://developers.google.com/apps-script/reference/url-fetch/url-fetch-app#fetchurl,-params

Is it that the `Content-Type` header must be removed, or the `Accept` header must be removed?

**Comment by SeanYang66** [comment]
The Accept header must be removed but is currently hard coded in the lib.

**Comment by SeanYang66** [comment]
Finally got the TD API to work end to end (from initial auth to make request, haven't try refresh token yet), another quirk I had to deal with is that although TD expects encoded URL, it sends back the token in JSON, and the library will try to parse the response as encoded URL since that's the token format I set on the service.

I'm new to JS and OAuth so I'm not sure if I didn't configure the service right or more options should be added to fit APIs like TD's

**Comment by erickoledadevrel** [comment]
Regarding the first issue, I think you should remove your call to `.setTokenFormat(OAuth2.TOKEN_FORMAT.FORM_URL_ENCODED)` and let it default to JSON. The input it always sent URL encoded, and this format specifies the expected response. It could be that this resolves your issue with the `Accept` header, since it would now correctly say we expect JSON.

Regarding the second issue, you can use the existing [`.setTokenPayloadHandler()`](https://github.com/googleworkspace/apps-script-oauth2#modifying-the-access-token-payload) method for this. You pass a function that modifies the payload before it's sent to the server, in your case adding the additional `access_type` parameter.

**Comment by SeanYang66** [comment]
You're right. Reverted both changes and it works fine. Thanks!

**Comment by erickoledadevrel** [comment]
Glad to hear it worked! If you have some extra time it would be great if you could contribute a sample showing how to connect to the TD Ameritrade API. Just copy one of the existing samples and set the correct parameters for that API.

**Comment by wampaTaco** [comment]
@SeanYang66 Any shot of posting you final code to authorize to the TD API?  I've been wrassling with this for a few days now.

**Comment by PravinrajV** [comment]
> @SeanYang66 Any shot of posting you final code to authorize to the TD API? I've been wrassling with this for a few days now.

Any luck with the sample code?
