### ISSUE TITLE
Capturing Authentication keys from redirect URL from facebook app login flow

### ISSUE THREAD

**Issue by weareantidote** [googleworkspace/apps-script-oauth2#271]
Good day,

I am currently still new to Java or app script and thus an infant with minimal knowledge, and experimenting with low code development, however, I am trying to create an app that captures Authentication keys that can be used on Facebook API to make a request for a low code application through Google app script, from what I have noticed the Authentication keys are usually on the address bar once redirected to the Url registered on the app that is on the Facebook developers platform settings, I tried using the libraries however usually encounter error problems, with error on the appscript running the code, mainly I usually simply copy and paste, and as I said minimal coding knowledge at this stage.

however, the function of this specific app script is to capture and store Authentication keys for use while requesting data from Facebook in integration with other application using API.

Would you kindly help with this

and also noticed that on the API URL you still use v2.6 while Facebook uses v9 this left me asking questions if the libraries are up to date

kind regards

**Comment by erickoledadevrel** [comment]
Unfortunately I don't have the time to consult on individual projects, nor is this issue tracker the appropriate venue. I suggest reaching out on the [Apps Script Community Forum](https://groups.google.com/g/google-apps-script-community), as there are many developers there with experience using this library.
