### ISSUE TITLE
"Token response not valid JSON" despite JSON being valid - Service_.parseToken_()

### ISSUE THREAD

**Issue by lewis-cobry** [googleworkspace/apps-script-oauth2#272]
I've successfully received an OAuth2 token from the HubSpot API, but when I call `Service_.handleCallback`, I get an 'Unexpected end of JSON input' error. This seems to be due to the `JSON.parse()` call in `parseToken_()`, but if I call `JSON.parse()` or `JSON.stringify()` on my input before passing it to `handleCallback()`, it works fine.

The response I am passing to `Service.handleCallback()` is in this form:
```
{
  "parameter": {
    "state": "xyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyz",
    "serviceName": "Hubspot",
    "code": "xyzxyz-xyzxyz-xyzxyz-xyzxyz-xyzxyzxyzxyz"
  },
  "parameters": {
    "code": [
      "xyzxyz-xyzxyz-xyzxyz-xyzxyz-xyzxyzxyzxyz"
    ],
    "state": [
      "xyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyz"
    ],
    "serviceName": "Hubspot"
  },
  "queryString": "xyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyz",
  "contentLength": -1,
  "contextPath": ""
}
```
Here's the error I get in Apps Script
![image](https://user-images.githubusercontent.com/77738889/111458533-6eeaaf80-8711-11eb-8e51-6cf401d9d52a.png)

**Comment by erickoledadevrel** [comment]
This error indicates that the response from the service's token endpoint isn't valid JSON. You've successfully retrieved an authorization code, but the failure is coming when you try to exchange that code for a token. The input to `handleCallback()` is the request context, which is not the thing that's being fed into `JSON.parse()`. Perhaps you've entered the incorrect token URL, and it's returning an HTML 404 response?

I've added a HubSpot sample to this library which is working correctly:

https://github.com/googleworkspace/apps-script-oauth2/blob/master/samples/HubSpot.gs

I suggest starting with that code as a baseline and see if that resolves your issue.

**Comment by lewis-cobry** [comment]
You're completely right, I had the wrong token URL. Thank you for your help, I appreciate it!
