### ISSUE TITLE
"This action is not available if you are connected to multiple accounts in the same domain or to multiple personal accounts. Please log out and try again."

### ISSUE THREAD

**Issue by DeplanqueMathis** [googleworkspace/apps-script-oauth2#277]
Hello,

Your library is verry powerfull and helpfull but I want to use OAuth2 to connect on an external Website and give the access to my gmail addon, it work perfectly when I'm using my addon with only one gmail account log on mail.google.com or if I use my default google account but if I use an other account it show me the error I wrote in the title. Any solution for my problem ? I can't use the solution of "privaty" or "anonymous" window, it's not covenient or professional :/

Thanks a lot for your answer !

**Comment by erickoledadevrel** [comment]
I haven't come across this error before, but it looks like it's coming from Apps Script itself and not this library. I do know that support for multilogin isn't great in Apps Script, but I don't know of anything you can do to work around it.
