### ISSUE TITLE
Auth Token flow does not complete - Exception: DNS エラー: http://SERVICE_AUTH_TOKEN_URL    

### ISSUE THREAD

**Issue by se-xiaoc** [googleworkspace/apps-script-oauth2#278]
When I use azure ad b2c for authentication, I have logged in successfully, but the callback error:
      Exception: DNS エラー: http://SERVICE_AUTH_TOKEN_URL
     at Service_.fetchToken_(Service:510:30)
     at Service_.handleCallback(Service:399:20)
How to solve it
![image](https://user-images.githubusercontent.com/70502987/116510562-aeeba780-a8f7-11eb-83ec-63faf4c2987b.png)

**Comment by erickoledadevrel** [comment]
It looks like you passed the wrong value to `setAuthorizationBaseUrl`.
