### ISSUE TITLE
refresh_token not stored

### ISSUE THREAD

**Issue by okigan** [googleworkspace/apps-script-oauth2#279]
Looks like refresh_token is not stored, it is used in the refresh method, but does not exist [1].

That being said, I could be wrong -- could you point to place where refresh_token is saved.

[1] https://github.com/googleworkspace/apps-script-oauth2/blob/27c61fcc15af19f9d6505d2a6170ff883f0bd868/src/Service.js#L586

**Comment by erickoledadevrel** [comment]
`refresh_token` is a field of the token response, and saved along with all of the other fields here: 

https://github.com/googleworkspace/apps-script-oauth2/blob/27c61fcc15af19f9d6505d2a6170ff883f0bd868/src/Service.js#L392-L400

There are some OAuth providers, Google being one, that only return the `refresh_token` under certain circumstances. For instance, when you request offline access and specify `prompt=consent`.
