### ISSUE TITLE
Unable to configure HTTP method for token request

### ISSUE THREAD

**Issue by Tasemo** [googleworkspace/apps-script-oauth2#284]
The HTTP method used in the token request is hard coded to POST and there seems to be no way of changing that. The current API I am working with only works with PUT requests (https://developers.pinterest.com/docs/redoc/combined_reporting/#section/User-Authorization/Exchange-the-code-for-an-access-token). If some OAuth standard requires this specific method, let me know and I will report the bug to the API maintainer. Thanks in advance!

**Comment by erickoledadevrel** [comment]
The spec does say they should use POST:

> The client MUST use the HTTP "POST" method when making access token requests.

https://datatracker.ietf.org/doc/html/rfc6749#section-3.2

That said, there is a lot of deviation from the spec in practice, and it's unlikely they will change. I can quickly add an option to override the default method used.

**Comment by erickoledadevrel** [comment]
I've published version 41 of the library, which includes a new `setTokenMethod()` method you can use. Let me know if that works.

**Comment by Tasemo** [comment]
@erickoledadevrel It works great, thanks for the quick response!
