### ISSUE TITLE
createService always launch auth for Google not the service specified

### ISSUE THREAD

**Issue by gpomp** [googleworkspace/apps-script-oauth2#286]
Hi,
When I load the lib (v41) and just copy what's in the sample for Github (also adding the vars for client id & secret):
```
/**
 * Configures the service.
 */
function getService() {
  return OAuth2.createService('GitHub')
      // Set the endpoint URLs.
      .setAuthorizationBaseUrl('https://github.com/login/oauth/authorize')
      .setTokenUrl('https://github.com/login/oauth/access_token')

      // Set the client ID and secret.
      .setClientId(CLIENT_ID)
      .setClientSecret(CLIENT_SECRET)

      // Set the name of the callback function that should be invoked to
      // complete the OAuth flow.
      .setCallbackFunction('authCallback')

      // Set the property store where authorized tokens should be persisted.
      .setPropertyStore(PropertiesService.getUserProperties());
}
```

Then just launch this function with the function selector in Google App Script, it launches the prompt to  authorize a Google account not Github.
Tried other services and looks like it's the same behavior.

Am I missing something?

Thanks!

**Comment by erickoledadevrel** [comment]
The dialog is coming form Apps Script the platform, as it needs to get your permission to make `UrlFetchApp` requests used by the library. You'd see the same screen if you just attempted to access a spreadsheet using the built-in services. It's only after you approve access that the script code runs.

**Comment by gpomp** [comment]
Thanks for your reply @erickoledadevrel.  
I understand if I need to have some Google permission but I'm still confuse at why I never see the prompt to authorize my Github app tho. I should see something like that, right? sohamkamani.com/static/bc2d386cce2c45e5b7f1f4b9aa885ff9/40040/oauth-example-screenshot-small.png
Am I missing something?

**Comment by erickoledadevrel** [comment]
Apps Script doesn't provide a hook for libraries to hook into the same dialog. If you look at the examples in this repo you'll see they either log the authorization URL, or if running in a UI show a link.

**Comment by gpomp** [comment]
aaah, right, ok I understand now. That's why it logs the url. Make sense.
Thanks to have taken the time to explain! Cheers.
