### ISSUE TITLE
Exception raises because corresponding URL has not been added to white list in manifest file

### ISSUE THREAD

**Issue by sebO-fr** [googleworkspace/apps-script-oauth2#312]
Hi there,

My custom Google Workspace add-on for connecting my account to one my Zoho application (Bigin CRM) raise an exception from this morning (I did not open it for a couple of weeks) after accepting the access to the Zoho account.

See screen shot attached.

It's first time from I installed it that the addon requests me to renew the authentication ?! I have been using the v40. I have tried updating to the v.41. It happens the same.

Could you please advise ?

Thanks !

Sébastien. 

![Screenshot 2021-06-30 13 02 55 - Display 2](https://user-images.githubusercontent.com/80100266/123950071-96edde00-d9a3-11eb-9ab8-8234e0631f37.png)

![Screenshot 2021-06-30 12 52 00 - Display 1](https://user-images.githubusercontent.com/80100266/123949411-d2d47380-d9a2-11eb-9627-a8741822c908.png)

**Comment by erickoledadevrel** [comment]
This seems similar to #311, where perhaps the enforcement of the `urlFetchWhitelist` changed in some way. Unfortunately that's outside the scope of what I can control in this library.
