### ISSUE TITLE
Not Receiving id_token

### ISSUE THREAD

**Issue by benlee20182018** [googleworkspace/apps-script-oauth2#322]
Hello: I am using this library for a Workspace add on that is connecting to a Google Cloud Function. I am using the json secret provided by the console. I execute the authorization flow and receive an access_token. However, when I try to us the id_token for UrlFetchApp.Fetch to invoke a restricted service, the id_token is 'undefined'. Any idea as to what I may be doing wrong? Thank you.

**Comment by therealchjones** [comment]
I had the same problem. It was remedied by adding the "openid" scope to my authorization request. I assume, but have not tested, that there are other scopes that achieve the same result; this appears to be the minimum one. It's "required" in the Google OAuth 2.0 request flow (see https://developers.google.com/identity/protocols/oauth2/openid-connect#scope-param), but I hadn't included it previously.

**Comment by benlee20182018** [comment]
Thank you very much for your answer!

**Comment by biowalker** [comment]
I am running into the same problem, but I am already specifying the "openid" scope.

```
function getOAuthService(user) {
  const properties = PropertiesService.getScriptProperties();
  const private_key = properties.getProperty("private_key").replace(/\\n/g, "\n");
  const client_email = properties.getProperty("client_email");
  const user_email = client_email;
  
  return OAuth2.createService('Service Account')
    .setTokenUrl('https://accounts.google.com/o/oauth2/token')
    .setPrivateKey(private_key)
    .setIssuer(client_email)
    .setSubject(user_email)
    .setParam('access_type', 'offline')
    .setScope('openid');
}
```

**Comment by biowalker** [comment]
Also, this is a service account. I am unsure how that factors into things here.
