### ISSUE TITLE
Error: Error retrieving token: access_denied, Unauthorized (line 553, file "Service")

### ISSUE THREAD

**Issue by fid9** [googleworkspace/apps-script-oauth2#365]
I keep receiving this error which is thrown inside **Service_.getTokenFromResponse_** function but I can't debug as to what exactly is it happening. What is the usual cause here?

Looked at some forums and their problem was due to an incorrect token URL however that is not the case for me.

**Comment by erickoledadevrel** [comment]
OAuth servers are generally opaque with the error messages, so it can be difficult to determine what the issue is. What API are you connecting to? What does your code look like?

**Comment by fid9** [comment]
The API i'm attempting to connect to is POST "..../oauth/token" and it seems like it's failing under fetchToken function url fetch. The obvious issue was the Token Endpoint Authentication Method on Auth0 which was defaulted to NONE but since we require a client secret, it should be switched to POST. However, it wasn't the case either.
In general, the code looks something like this: [https://codeburst.io/simple-oauth-in-google-apps-script-d21f88cf63c4](url) (6th header)

**Comment by charanjit-mtech** [comment]
What was OAuthTokenURL in your case?
