### ISSUE TITLE
Error: "Google Apps Script: Exception: You do not have permission to perform that action" 

### ISSUE THREAD

**Issue by Shree-hari** [googleworkspace/apps-script-oauth2#409]
This error started coming after some major updates were added to my add-on, one of them was time trigger. Please help me resolve this issue as this problem has no solution available on web as of now.

![image](https://user-images.githubusercontent.com/31119605/197041144-99506ff3-111d-4fa7-a55c-ac4b0bca8ab6.png)

**Comment by Shree-hari** [comment]
While testing it in Head deployment of my add-on, it was working properly.

As soon as I published it, it shows this error to users how install it.

**Comment by Shree-hari** [comment]
Issue was resolved after I added all the required scopes to "appsscript.json", you can find this file after you turn it on by going in settings of the appscript.

**Comment by freaki7** [comment]
authorize me
