### ISSUE TITLE
Google Gmail Addons card doesn't refresh after OAuth 2.0 authorization

### ISSUE THREAD

**Issue by AlexNetsvetov** [googleworkspace/apps-script-oauth2#436]
After authorization success path card doesn't refresh and I can't see actual content.

I checked some available addons in Google Shop (like Zoom, Dropbox etc.) and they have the same problem. How I can refresh a card after success authorization?

I found out that Safari works fine. But Firefox, Edge and Google Chrome have this bug. That looks like additional refresh in "Chromium" browsers 

Versions:
- Safari: 16.3 (18614.4.6.1.5)
- Chrome: 109.0.5414.119 (Official Build) (arm64)

Thanks for help!

```
function getClient() {
...
 return OAuth2.createService('myService')
    .setAuthorizationBaseUrl(
      `${url}/${prefix}/oauth2-token/authorize`
    )
    .setTokenUrl(`${url}/oauth2-token`)
    .setClientId(clientId)
    .setClientSecret(clientSecret)
    .setCallbackFunction('handleOAuthResponse')
    .setPropertyStore(PropertiesService.getUserProperties())
    .setCache(CacheService.getUserCache())
    .setLock(LockService.getUserLock())
    .setGrantType('authorization_code');
}

function handleOAuthResponse(request) {
  const client = getClient();

  const authorized = client.handleCallback(request);

  if (authorized) {
    return HtmlService.createHtmlOutput('Success!');
  } else {
    return HtmlService.createHtmlOutput('Denied.');
  }
}

 function createAuthorizationCard() {
  const client = getClient();

  ....
  const connectButton = CardService.newTextButton()
    .setText(locales[LOCALE_KEY.setup_connect]);

    const authUrl = client.getAuthorizationUrl();
    const authAction =
      CardService.newAuthorizationAction().setAuthorizationUrl(authUrl);
    connectButton.setAuthorizationAction(authAction);

 ...

const section = CardService.newCardSection()
    .addWidget(connectButton);

  const card = addMenuItemsToCard(
    CardService.newCardBuilder().setHeader(header).addSection(section)
  );

return card.build();
}

function createHomeCard() {
 //Some code
}

 function onHomePageOpen() {
   const client = getClient();

    if (!client?.hasAccess()) {
      return createAuthorizationCard();
    }

    return createHomeCard();
}
```

**Comment by AlexNetsvetov** [comment]
I make some logs.
This is how it work for Chrome. It looks like refresh was called before handled OAuth response.

<img width="1363" alt="google chrome flow" src="https://user-images.githubusercontent.com/115094034/220658279-bb4b26f3-5ce0-4ddb-b5f2-3ffa9e753566.png">

For Safari.
<img width="1334" alt="safari flow" src="https://user-images.githubusercontent.com/115094034/220658696-ab6312bd-c5a9-49f3-9fad-57a8bfa5597f.png">

**Comment by sqrrrl** [comment]
This is an issue with the add-on framework itself, not the oauth library. A recent Chrome fix revealed an issue with how the popups work and the mechanism used to detect if they're closed isn't reliable. 

The OnCload/Reload option is being reworked to require a manual refresh by the user. This should already be available now though the text is being reworked to make it a little clearer to users.

Still hopeful that team can find a better long term solution, but given a lot of add-ons were impacted, prompting the user to refresh was the fastest route to a fix.

**Comment by AlexNetsvetov** [comment]
Okay, thanks for your answer!
