### ISSUE TITLE
NoLibrary: Running in Apps Script with 403 error

### ISSUE THREAD

**Issue by cvalcarcel** [googleworkspace/apps-script-oauth2#443]
I am looking to make Form API calls from Google Sheets without having to create a GCP project. 

After many failed attempts I decided to try the NoLibrary approach given that no API or project was needed to make it work. I copied the appscript.json and Code.gs to a fresh project and ran it. I have run this in Chrome, Firefox, and incognito windows of each.

What I get when I run Code.gs from the Apps Script editor (and I allow the script access to the GSheet which is telling me that OAuth is being satisfied) is:

"Google Search Console API has not been used in project 311386532115 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/searchconsole.googleapis.com/overvie…"

Any thoughts? Thanks!

**Comment by erickoledadevrel** [comment]
The error message there sort of gives you the solution. In order to make the API request you are making you need to enable the API for your GCP project, which you can do by following the link.

**Comment by cvalcarcel** [comment]
The project number it mentions doesn't exist. I thought your example didn't need a project and the API certainly doesn't need an API key. The test was to see that it was possible to make an API call using OAuth, but without the overhead of a project. Are you saying that API calls cannot be made without a project? Someone who simply wants to write a simple Apps Script has to create a GCP account and then a GCP project? Seems like significant overhead for a trivial example.

**Comment by erickoledadevrel** [comment]
@cvalcarcel - That is likely the project number for the default project that came with the script. You can toggle on advanced services for your script, but if you need to use an API that doesn't have a corresponding advanced service then you'll need to swap in your own GCP project, where you can enable the API manually. You can read more about projects in scripts here:

https://developers.google.com/apps-script/guides/cloud-platform-projects

**Comment by cvalcarcel** [comment]
I finally figured that out on my own. For some reason GH did not send me a notification of your reply. Being a casual AS user I did not know that each project had its own secret GCP project. The error message only added to the confusion since I had no idea all AS projects are assigned a GCP project by default.
Oh, well. Thanks for responding! :)
