### ISSUE TITLE
Error: Access not granted or expired. Service_.getAccessToken	@ Service.gs:518

### ISSUE THREAD

**Issue by andrewpollock** [googleworkspace/apps-script-oauth2#447]
Hi,

I'm trying to follow https://hawksey.info/blog/2016/08/working-with-github-repository-files-using-google-apps-script-examples-in-getting-writing-and-committing-content/ to use App Script with the GitHub API.

I've taken a copy of https://script.google.com/corp/home/projects/1jI_BpCFqKstGFQ8sNY8nJwjOiXXhubKDvD7G9h6U1iE63mzX2e4U-ak_/edit and I believe I've set up a GitHub OAuth2 application scope correctly.

On first run, I am prompted to authorize my application, and then I get:

```
Error: Access not granted or expired.
Service_.getAccessToken	@ Service.gs:518
(anonymous)	@ Code.gs:19
_request	@ Code.gs:256
self_.Repository.getMetadata	@ Code.gs:485
testGettingRepoMetadata	@ Code.gs:22
```

which correlates to this code:

```
function getGithubService_() {
    return OAuth2.createService('GitHub')
        .setAuthorizationBaseUrl("https://github.com/login/oauth/authorize")
        .setTokenUrl("https://github.com/login/oauth/access_token")
        .setClientId(PropertiesService.getScriptProperties().getProperty('git_clientId'))
        .setClientSecret(PropertiesService.getScriptProperties().getProperty('git_clientSecret'))
        .setScope(['repo'])
        .setCallbackFunction('authCallbackGit')
        .setPropertyStore(PropertiesService.getUserProperties())
}
```

I have set up the `git_clientId` and `git_clientSecret` as script properties per the instructions.

**Comment by lucasgburbling** [comment]
> Oi,
> 
> Estou tentando seguir [https://hawksey.info/blog/2016/08/working-with-github-repository-files-using-google-apps-script-examples-in-getting-writing-and-committed- content/](https://hawksey.info/blog/2016/08/working-with-github-repository-files-using-google-apps-script-examples-in-getting-writing-and-committing-content/) para usar o App Script com a API do GitHub.
> 
> Fiz uma cópia de https://script.google.com/corp/home/projects/1jI_BpCFqKstGFQ8sNY8nJwjOiXXhubKDvD7G9h6U1iE63mzX2e4U-ak_/edit e acredito que configurei um escopo de aplicativo GitHub OAuth2 corretamente.
> 
> Na primeira execução, sou solicitado a autorizar meu aplicativo e recebo:
> 
> ```
> Error: Access not granted or expired.
> Service_.getAccessToken	@ Service.gs:518
> (anonymous)	@ Code.gs:19
> _request	@ Code.gs:256
> self_.Repository.getMetadata	@ Code.gs:485
> testGettingRepoMetadata	@ Code.gs:22
> ```
> 
> que se correlaciona com este código:
> 
> ```
> function getGithubService_() {
>     return OAuth2.createService('GitHub')
>         .setAuthorizationBaseUrl("https://github.com/login/oauth/authorize")
>         .setTokenUrl("https://github.com/login/oauth/access_token")
>         .setClientId(PropertiesService.getScriptProperties().getProperty('git_clientId'))
>         .setClientSecret(PropertiesService.getScriptProperties().getProperty('git_clientSecret'))
>         .setScope(['repo'])
>         .setCallbackFunction('authCallbackGit')
>         .setPropertyStore(PropertiesService.getUserProperties())
> }
> ```
> 
> Eu configurei o `git_clientId`e `git_clientSecret`como propriedades de script de acordo com as instruções.

Estou com mesmo problema

**Comment by erickoledadevrel** [comment]
@andrewpollock - You need to run `getGithubAuthURL()` first, which logs a URI to the logs. Open that URL and approve access. Then you should be able to get an access token.

**Comment by andrewpollock** [comment]
Thanks @erickoledadevrel that was the problem, works a treat now.
