### ISSUE TITLE
Redirect URIs in the context of add-ons installed on various sheets/users.

### ISSUE THREAD

**Issue by mpenna** [googleworkspace/apps-script-oauth2#464]
I'm not sure if this is even an issue or what, but I'm having a hard time wrapping my head around and unpacking this scenario: how should we handle the redirect URI for an add-on which relies on an OAuth flow in order to integrate some third-party API, given that the add-on can and will be installed on various sheets, various users? Given that the third-party API most certainly will require these callback URIs to be registered/authorized beforehand, it wouldn't be feasible to register every single sheet callback URI, right? How should this then be tackled? 

Perhaps this is due to a less than par level of understanding of the add-on architecture, its inner-workings and such, but I thought some clarification on such a scenario could help others also.

**Comment by erickoledadevrel** [comment]
The redirect URL is relative to the add-on, not the sheet, so the URL stays the same regardless of which sheet it's installed into. The add-on connects to the spreadsheet, but all of the artifacts are fully portable.

**Comment by mpenna** [comment]
Thank you, @erickoledadevrel for the quick response and clarification. Let me then further a bit this topic with you. Would it be correct to say that it's more or less like a client-server architecture, where the frontend/client in this case would be the sheet itself while the backend/server would be the GAS project deployed as an add-on, having the latter a well-known URL? 

We have recently deployed a GAS project as an add-on (still under review), albeit one still in a very early alpha stage, and we have configured its deployment URL as the redirect URI back at the third-party API. We managed to get the OAuth flow to work, nevertheless the callback/redirection from the API is being captured at the `doGet` simple trigger back at the GAS project. Is this the proper way to handle this? We're not using the OAuth2 lib.

**Comment by erickoledadevrel** [comment]
> it's more or less like a client-server architecture, where the frontend/client in this case would be the sheet itself while the backend/server would be the GAS project deployed as an add-on, having the latter a well-known URL?

Ya, that's a close enough analogy I guess.

> the callback/redirection from the API is being captured at the `doGet` simple trigger back at the GAS project. Is this the proper way to handle this? We're not using the OAuth2 lib.

You can use the `doGet` function for this, but the better route (and the one used by this library) is to use the script's `/usercallback` endpoint. It supports / requires a state token, which helps prevent against certain forms of attack. You can read more about it here:

https://developers.google.com/apps-script/reference/script/script-app#newstatetoken

> How then do installable triggers fit into this picture? If I'm depicting this correctly, the add-on would be a shared instance, but the triggers are installed per user / per document, right?

That's correct, the core of the add-on is central, but installable triggers are an artifact that is attached to the spreadsheet.

**Comment by mpenna** [comment]
Thank you for clarifying and for your patience.

**Comment by mpenna** [comment]
Hi @erickoledadevrel I hope you don't mind clarifying a couple other topics in relation to what we've been discussing so far.

Regarding the add-on's unique URL, I've noticed that this library relies on the `getscriptid()` method of the ScriptApp API when putting together the redirect URL (https://developers.google.com/apps-script/reference/script/script-app#getscriptid). Is it then safe to say that this method will indeed return the add-on's unique/persistent URL, rather than the current document's where it has been installed onto?

Along these same lines, I'd appreciate if you could help me better understand the attention points that we should be aware of, considering that, and if I'm getting all this right, the (same) authentication callback handling logic will be shared amongst everyone using the add-on, right? Do we need to implement some sort of locking mechanism to protect against concurrency or is this perhaps taken care of in some other way by the execution environment itself?

The same also applies when it comes to trigger execution. You already explained that installable triggers and other artifacts are fully portable, meaning that they're instantiated/installed per spreadsheet and per user, right? However, I'm still a bit confused trying to figure out what happens when these triggers run. Will they all share the same (add-on) code instance and context or will each one run under its own context? Again, will concurrency come into play and how to best handle this if it does? 

Once again, thanks and sorry for posting this new batch of questions, but it's a bit hard figuring this all out by yourself.

**Comment by erickoledadevrel** [comment]
> Is it then safe to say that this method will indeed return the add-on's unique/persistent URL, rather than the current document's where it has been installed onto?

Yes, that is correct.

> if I'm getting all this right, the (same) authentication callback handling logic will be shared amongst everyone using the add-on, right? Do we need to implement some sort of locking mechanism to protect against concurrency or is this perhaps taken care of in some other way by the execution environment itself?

The same mechanism, but in most cases you want to use different storage. For instance, if you pass in UserProperties as the properties store then each user will be storing and retrieving their own personal tokens. It is possible to use ScriptProperties or DocumentProperties if you desire to share tokens between users.

> Will they all share the same (add-on) code instance and context or will each one run under its own context? Again, will concurrency come into play and how to best handle this if it does?

That's correct, the code is shared but the context (`SpreadsheetApp.getActiveSpreadsheet()`, etc) is different. You generally don't need to worry about concurrency.

**Comment by mpenna** [comment]
Great. I'll try to test these scenarios out to make sure that concurrency won't interfere, but it's good to know that context segregation is already part of the picture.

Once again, thanks. 

If you don't mind, I'll leave this issue open for now, just in case further assistance is needed.

**Comment by mpenna** [comment]
One thing that already sprung to mind is: what about local or in-scope variables? Should we consider these structures as being thread-safe or will they also be shared, along with the code itself?

**Comment by erickoledadevrel** [comment]
That's all thread-safe. It's a low-code scripting language, so it's mostly just write the code and go. There is a `LockService` you can use to make sure multiple threads don't modify a document or other shared resource at once, but the need for that is rare.

I'd suggest closing this issue, since it's strayed far from the original purpose of asking about this OAuth2 library. I'd suggest posting questions about Apps Script to the community: https://groups.google.com/g/google-apps-script-community

**Comment by mpenna** [comment]
Sure. I'll refer to the forums in case further questions arise. 

Thank you for the help and guidance.

**Comment by mpenna** [comment]
Sure. I'll refer to the forums in case further questions arise.

Thank you for the help and guidance.
